program ::= def | command | program

def ::= def_const | def_var | def_arr | def_func
def_const ::= NUMBER DEF_CONST WORD
def_var ::= DEF_VAR WORD
def_arr ::= DEF_VAR WORD NUMBER MEM_CELLS MEM_ALLOC

def_func ::= FUNC_BEGIN WORD body FUNC_END
body ::= command | if_expr | for_expr | while_expr | body

if_expr ::= COND_IF body COND_THEN | COND_IF body COND_ELSE body COND_THEN
for_expr ::= FOR_BEGIN body FOR_END
while_expr ::= WHILE_BEGIN body WHILE_END

command ::= WORD | cmd_compare | cmd_calc | cmd_io | cmd_mem

cmd_mem ::= MEM_FETCH | MEM_STORE | MEM_STORE_INC
cmd_compare ::= CMP_EQ | CMP_LT | CMP_GT
cmd_calc ::= MATH_ADD | MATH_SUB | MATH_DIV | MATH_MUL | MATH_MOD | LOG_INV | LOG_AND | LOG_OR
cmd_io ::= IO_IN | IO_OUT_STR | IO_OUT_INT | IO_OUT_CHAR | IO_OUT_CR
