program ::= program | definition | function | command

function ::= FUNC_BEGIN WORD func_body FUNC_END
func_body ::= func_body | command | if_expr | for_expr | while_expr

if_expr ::= COND_IF func_body COND_THEN | COND_IF func_body COND_ELSE func_body COND_THEN
for_expr ::= FOR_BEGIN func_body FOR_END
while_expr ::= WHILE_BEGIN func_body WHILE_END


definition ::= def_const | def_var | def_arr
def_const ::= NUMBER DEF_CONST WORD
def_var ::= DEF_VAR WORD
def_arr ::= DEF_VAR WORD NUMBER MEM_CELLS MEM_ALLOC


command ::= cmd_call | cmd_compare | cmd_calc | cmd_io | cmd_mem
cmd_call ::= WORD
cmd_mem ::= MEM_FETCH | MEM_STORE | MEM_STORE_INC
cmd_compare ::= CMP_EQ | CMP_LT | CMP_GT
cmd_calc ::= MATH_ADD | MATH_SUB | MATH_DIV | MATH_MUL | MATH_MOD | LOG_INV | LOG_AND | LOG_OR
cmd_io ::= IO_IN | IO_OUT_STR | IO_OUT_INT | IO_OUT_CHAR | IO_OUT_CR
